435/swap es querybuilder with bodybuilder
hochschule-darmstadt/openartbrowser pull request #456
Opened 2021-01-03 14:25 UTC by EeveesEyes

This replaces the es-query-builder with the bodybuilder package, which supports all kinds of elasticsearch queries. #435

2021-01-04 16:27 UTC, mauamy requested changes

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> -    const query = new QueryBuilder().size(400);
You removed the size(400) part from the query (what is in my opinion very logical). But just to clearify: Is this intentional?

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +      .sort(defaultSortField, 'desc')
Missing `;`
```suggestion
      .sort(defaultSortField, 'desc');
```

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +      .from(from)
Missing `;`
```suggestion
      .from(from);
```

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +      .size(count)
Missing `;`
```suggestion
      .size(count);
```

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +          .orQuery('match', 'description', keyword)
Missing `;`
```suggestion
          .orQuery('match', 'description', keyword);
```

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +      .size(200)
Missing `;`
```suggestion
      .size(200);
```

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +      .size(count)
Missing `;`
```suggestion
      .size(count);
```

2021-01-04 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +  public async searchArtworks(searchObj: ArtSearch, keywords: string[] = []): Promise<Artwork[]> {
Is there any reason for this being an `async` function?

2021-01-11 19:43 UTC, EeveesEyes commented on app/src/app/core/services/elasticsearch/data.service.ts
> -    const query = new QueryBuilder().size(400);
No, not intentional :)

2021-01-28 11:51 UTC, mauamy requested changes

2021-01-28 11:51 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
>        .size(5)
We should pass this size as an additional parameter since it might be use for other use-cases in the future

2021-01-29 16:27 UTC, mauamy requested changes
All requested changes are related to `.size(...)` calls where the size parameter is not yet a parameter of the surrounding function and therefore is hard-coded in the corresponding call. 
Since I did not find any pattern or reason why these are hard-coded while other are passed as parameters I suggest to move every `size` to the parameters of the functions. If there is a specific reason / pattern I missed it is of course open for discussion.

2021-01-29 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
>        .size(200);
I would  move this size as well to a function parameter to keep consistency.

2021-01-29 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
>        .size(400)
I would  move this size as well to a function parameter to keep consistency.

2021-01-29 16:27 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +    const body = bodyBuilder().size(400);
I would  move this size as well to a function parameter to keep consistency.

2021-02-01 14:34 UTC, mauamy approved these changes

2021-02-01 14:49 UTC, merged