Feature/422/fl for entity pages test
hochschule-darmstadt/openartbrowser pull request #460
Opened 2021-01-29 12:31 UTC by EeveesEyes

Implements #422 and #459

2021-02-02 19:37 UTC, mauamy requested changes
Here are some points in addition to the commented lines:

#### 1. Page-/Tab-Parameter in Request URL leads to weird behaviour of the browser's return back function
If you switch between the timeline and artworks tab of e.g. an artist, the URL parameters changes accordingly. But it seems like these changes are added to the browser's history and therefore if you click on the browser's back button it only changes the URL parameters back but nothing else changes. 

#### 2. Page Parameter Offset by 1
The `page` parameter in the URL is always off by 1. I think we should change this so that the URL parameter value matches the shown page of the paginator, to prevent user confusion.

2021-02-02 19:37 UTC, mauamy commented on app/src/app/shared/components/fetching-list/fetching-list.component.ts
> +        const pagesToCheck = this.range(Math.max(+this.currentPage - 2, 0), Math.min(+this.currentPage + 2, this.maxPage));
I think this `+-2`  should become a variable (maybe something like `loadingDistance or similar) instead of a hard-coded value.

2021-02-10 16:45 UTC, mauamy requested changes

2021-02-10 16:45 UTC, mauamy commented on app/src/app/core/services/elasticsearch/data.service.ts
> +    this.countEndPoint = environment.elastic.base + '/' + (this.ISO_639_1_LOCALE || 'en') + '/_count';
I would keep the `baseUrl` and just append for the endpoints:
```suggestion
    this.baseUrl = environment.elastic.base + '/' + (this.ISO_639_1_LOCALE || 'en')';
    this.searchEndPoint = this.baseUrl + '/_search';
    this.countEndPoint = this.baseUrl + '/_count';
```

2021-02-10 17:41 UTC, EeveesEyes commented on app/src/app/core/services/elasticsearch/data.service.ts
> +    this.countEndPoint = environment.elastic.base + '/' + (this.ISO_639_1_LOCALE || 'en') + '/_count';
Not sure if I understand your point correctly, but does it make a difference? It would just be a duplicate of environment.elastic.base I guess, so I think this is as good as having both endpoints.

2021-02-10 18:42 UTC, mauamy approved these changes

2021-02-10 19:45 UTC, merged