309/animated timelines
hochschule-darmstadt/openartbrowser pull request #489
Opened 2021-05-05 08:20 UTC by ahmadf0311

This branch fixes the issue #309.
Timer is defined in ngOnInit() and next slide will be shown after 5 second. If the last slide is shown set the values  of slideStart  on null and SliderItems is updated.

2021-05-05 12:31 UTC, tpachmann commented on app/src/app/shared/components/timeline/timeline.component.ts
> -      if(isAutomatic) {
This change means that the slider does not only jump back to the start on the automatic rotations (if the end of the list has been reached), but also when the user clicks on the next button.
I don't know whether this is intended behavior - since this hasn't been the case before our changes and no equal behavior is implemented for the backwards direction (when clicking the button on the left)..

2021-05-06 07:51 UTC, EeveesEyes commented on app/src/app/shared/components/timeline/timeline.component.ts
> -      if(isAutomatic) {
I think for user interaction both options would be acceptable (jumping to the start/end page or stopping at each end) but jumping to the start/end should be implemented bidirectional (backwards direction too) when the first option is implemented. The second option also has its pros, it's a matter of opinion i guess.

2021-05-12 09:29 UTC, EeveesEyes requested changes
See comment above

2021-06-03 12:03 UTC, tpachmann approved these changes
I've just fixed the issue with the prev button (now the slider should jump back to the end upon the _first_ click on the prev button at the beginning of the timeline). Also, I've added the timer reset to the `prevClicked` handler too.

2021-06-06 18:28 UTC, EeveesEyes requested changes
Unfortunately, on pressing 'back' on the first slide, the carousel tends to jump to other slides than the last one. One example: movement/Q610687?tab=timeline
Furthermore, actions on the slider do not reset the timer.
Lastly, please set the timer to 10 seconds, 5 is too short for the user

Sorry for my late review btw

2021-06-07 14:16 UTC, EeveesEyes approved these changes
Everything works :ok_hand: very nice

2021-06-07 15:47 UTC, merged