Mobile Overhaul: Text Styling
hochschule-darmstadt/openartbrowser pull request #530
Opened 2021-06-16 12:52 UTC by tpachmann

This PR should fix / implement the issue #498 (Mobile Overhaul: Adjust heading sizes & text overflow).

The font size for headings has been generally decreased and various overflow (ellipsis) rules have been added.

2021-06-21 14:41 UTC, DPhuongHda commented on app/src/styles/styles.scss
> +}
add newline

2021-06-21 14:41 UTC, DPhuongHda commented on app/src/app/pages/data-protection/data-protection.component.scss
> +}
add newline

2021-06-21 14:44 UTC, DPhuongHda requested changes
Looks good :) , maybe just add the missing newlines in the css files and then the pr can be merged.

2021-06-23 13:01 UTC, tpachmann commented
Done :) Just out of interest: Is this a convention in this repo or otherwise preferable?

2021-06-23 16:19 UTC, DPhuongHda commented
> Done :) Just out of interest: Is this a convention in this repo or otherwise preferable?

It is a general convention. Github is also displaying a small message if a new line is missing at the end of a file (review page).

2021-06-23 16:20 UTC, DPhuongHda approved these changes

2021-06-24 08:09 UTC, merged