#527 Implements retries while fetching the wikipedia extracts.
hochschule-darmstadt/openartbrowser pull request #545
Opened 2021-06-28 09:00 UTC by SpaceDave42

#527 Each time a language and type extract fails the script tries again with a smaller batch size. This also changes request_utils.py as this script handled the error caused by the chunk size being too large by calling exit(-1), completely stopping the crawl which is less than ideal.

This has been tested in branch 524 and is working as intended.

2021-06-28 14:22 UTC, EeveesEyes requested changes
Consider my comment - other than that, this is ready to go :+1:

2021-06-28 14:22 UTC, EeveesEyes commented on etl/data_extraction/get_wikipedia_extracts.py
> +                            chunk_size -= 5
I think we should increase the chunk_size again after successful fetches, but no further than 20. 
When one of the first chunks fails and the chunk size is lowered to 5, the rest of the fetching will take ages.

2021-06-29 08:07 UTC, SpaceDave42 commented on etl/data_extraction/get_wikipedia_extracts.py
> +                            chunk_size -= 5
Good idea

2021-06-29 08:08 UTC, SpaceDave42 commented
I pushed an increase to the chunk size after a successful chunk as long as it it <20.

2021-06-29 10:13 UTC, EeveesEyes approved these changes
:ok_hand:

2021-06-29 12:13 UTC, merged